core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('smartgallery.urls')),
]

admin.site.site_header = "SmartGallery CMS"
admin.site.site_title = admin.site.site_header
admin.site.index_title = f"Welcome to {admin.site.site_header}"

core/smartgallery/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index_page, name='index_page'),
    path('p/about/', views.about, name='about'),
    path('<slug:album_slug>/', views.show_albums, name='show_albums'),
    path('sys/<int:album_id>', views.edit_album, name='edit_album'),
    path('sys/delete_image/<int:image_id>', views.delete_image, name='delete_image'),
    path('sys/delete_all_album_images/<int:album_id>/', views.delete_all_album_images, name='delete_all_album_images'),
    path('sys/delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('sys/delete_all_album_hidden_images/<int:album_id>/', views.delete_all_album_hidden_images, name='delete_all_album_hidden_images'),
    path('sys/create_album/', views.create_album, name='create_album'),
    path('sys/update_image_order', views.update_image_order, name='update_image_order'),
    path('sys/update_image_name/<int:photo_id>', views.update_image_name, name='update_image_name'),
    path('sys/update_image_exif/<int:photo_id>', views.update_image_exif, name='update_image_exif'),
    path('sys/change_album/<int:photo_id>/<int:album_id>', views.change_album, name='change_album'),
    path('sys/images/<int:image_id>/change_visibility', views.change_visibility, name='change_visibility'),
    path('sys/login', views.a_login, name='a_login'),
    path('sys/logout/', views.a_logout, name='a_logout'),
    path('sys/settings', views.site_settings, name='site_settings'),
    path('sys/template_settings', views.template_settings, name='template_settings'),
    path('sys/menu_settings', views.menu_settings, name='menu_settings'),
    path('sys/social_settings/', views.social_settings, name='social_settings'),
    path('sys/user_settings/', views.user_settings, name='user_settings'),
    path('sys/update_menu_order/', views.update_menu_order, name='update_menu_order'),
    path('sys/update_social_order/', views.update_social_order, name='update_social_order'),
    path('sys/update_menu_item_name/', views.update_menu_item_name, name='update_menu_item_name'),
    path('sys/update_social_item_name/', views.update_social_item_name, name='update_social_item_name'),
    path('sys/delete_social_item_name/<int:id>', views.delete_social_item_name, name='delete_social_item_name'),
    path('sys/delete_current_logo/', views.delete_current_logo, name='delete_current_logo'),
    path('p/timeline/', views.timeline, name='timeline'),
    path('sys/upload/', views.upload_images, name='upload_images'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/smartgallery/models.py
import datetime
import os
import pillow_avif
from PIL import Image
from io import BytesIO
from PIL import ImageOps
from PIL.ExifTags import TAGS
from PIL import Image as PILImage, ExifTags
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models


class SiteSettings(models.Model):
    title = models.CharField(verbose_name=_('Website title'), max_length=100, blank=True, default='Smart Photo Gallery')
    logo = models.FileField(verbose_name=_('Site logo'), upload_to='logo/', blank=True)
    logo_width = models.PositiveIntegerField(verbose_name=_('Logo width, px'), blank=True, default=240)
    topbar_bgcolor = models.CharField(verbose_name=_('Top bar Background Color'), max_length=8, default="#B7C3F3", blank=True)
    topbar_fcolor = models.CharField(verbose_name=_('Top bar Font Color'), max_length=8, default="black", blank=True)
    copyright = models.CharField(
        verbose_name=_('Copyright text'),
        max_length=1000,
        blank=True,
        default=f'Smart Photo Gallery - {datetime.datetime.now().year}'
    )
    menu_delimiter = models.CharField(verbose_name=_('Menu delimiter'), max_length=5, blank=True, default=' | ')
    title_delimiter = models.CharField(verbose_name=_('Title delimiter'), max_length=5, blank=True, default=' · ')
    title_size = models.PositiveIntegerField(verbose_name=_('Title size, h1-6'), blank=True, default=2)
    menu_items_size = models.PositiveIntegerField(verbose_name=_('Menu item size, pt'), blank=True, default=18)
    image_long = models.PositiveIntegerField(verbose_name=_('Big image long side, px'), blank=False, default=1600)
    thumbnail_long = models.PositiveIntegerField(verbose_name=_('Preview long side, px'), blank=False, default=800)
    image_quality = models.PositiveIntegerField(verbose_name=_('Big image quality, %'), blank=False, default=90)
    thumbnail_quality = models.PositiveIntegerField(verbose_name=_('Preview image quality, %'), blank=False, default=80)
    preserve_image_size = models.BooleanField(verbose_name=_('Preserve big image size and quality'), default=False)
    show_social_links = models.BooleanField(verbose_name=_('Show social links'), default=False)
    show_about_page = models.BooleanField(verbose_name=_('Show About Me'), default=False)
    show_timeline_page = models.BooleanField(verbose_name=_('Show Timeline'), default=False)
    favicon = models.FileField(verbose_name=_('Favicon'), upload_to='favicon/', max_length=250, blank=True)
    LANGUAGE_CHOICES = [
        ('en', 'English'),
        ('ru', 'Russian'),
    ]
    default_language = models.CharField(
        verbose_name=_('Default Language'),
        max_length=2,
        choices=LANGUAGE_CHOICES,
        default='en',  # Set the default language
    )
    gle_analytics = models.TextField(verbose_name=_('Google analytics code'), max_length=1000, blank=True)
    index_content = models.TextField(verbose_name=_('Index page content'), max_length=20000, blank=True, default='')
    about_content = models.TextField(verbose_name=_('About me page content'), max_length=20000, blank=True, default='')

    def render_index_content(self, context=None):
        from django.template import Template, Context

        if context is None:
            context = {}

        template = Template(self.index_content)
        context = Context(context)
        return template.render(context)

    def render_about_content(self, context=None):
        from django.template import Template, Context

        if context is None:
            context = {}

        template = Template(self.about_content)
        context = Context(context)
        return template.render(context)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Site settings')
        verbose_name_plural = _('Site settings')


class SocialLinks(models.Model):
    name = models.CharField(verbose_name=_('Name'), max_length=80, blank=False)
    link = models.CharField(verbose_name=_('Link'), max_length=200, blank=True)
    icon = models.CharField(verbose_name=_('Icon'), max_length=100, blank=True)
    order = models.PositiveIntegerField(verbose_name=_('Order'), default=0)

    def __str__(self):
        return str(self.name)

    def publish(self):
        self.save()

    class Meta:
        verbose_name = _('Social Link')
        verbose_name_plural = _('Social Links')


class Album(models.Model):
    slug = models.CharField(verbose_name=_('SLUG'), max_length=128, blank=False, null=False)
    name = models.CharField(verbose_name=_('Album name'), max_length=128, blank=False, null=False)
    meta_tags = models.CharField(verbose_name=_('Meta keywords'), max_length=1000, blank=True)
    meta_desc = models.CharField(verbose_name=_('Meta description'), max_length=1000, blank=True)
    desc = models.TextField(
        verbose_name=_('About album'),
        max_length=2000,
        default='Album description can be changed in Album settings',
        blank=True,
        null=True
    )
    desc_visible = models.BooleanField(verbose_name=_('Description visibility'), default=True)
    cols_count_s = models.PositiveIntegerField(verbose_name=_('Columns count on mobile devices'), default=2)
    cols_count_m = models.PositiveIntegerField(verbose_name=_('Columns count'), default=3)
    cols_gap_size = [
        ('cl', "collapse"),
        ('sm', "small"),
        ('md', "medium"),
        ('lg', "large"),
    ]
    cols_gap = models.CharField(
        verbose_name=_('Columns gap'),
        max_length=2,
        choices=cols_gap_size,
        default='sm',
    )
    grid_types = [
        ('grid', "grid"),
        ('masonry', "masonry (beta)"),
    ]
    grid_type = models.CharField(
        verbose_name=_('Grid type'),
        max_length=10,
        choices=grid_types,
        default='grid',
    )
    masonry_text_overlay = models.BooleanField(verbose_name=_('Masonry text overlay'), default=True)
    image_border_radius = models.PositiveIntegerField(verbose_name=_('Images border radius, px'), default=0, blank=False)
    order = models.PositiveIntegerField(verbose_name=_('Order'), blank=True, null=True, default=0)
    status = models.BooleanField(verbose_name=_('Visibility'), default=True)
    transitions = [
        ('fade', "fade"),
        ('slide', "slide"),
        ('scale', "scale"),
    ]
    transition_anim = models.CharField(
        verbose_name=_('Image transition'),
        max_length=6,
        choices=transitions,
        default='slide',
    )
    cover = models.ImageField(upload_to='album_covers', blank=True, null=True)
    cover_visible = models.BooleanField(verbose_name=_('Cover visibility'), default=False)

    def resize_and_crop_cover(self, cover_long, cover_quality):
        # Open the original image using PIL
        pil_image = PILImage.open(self.cover.path)

        if pil_image.format in ["WEBP", "HEIC"]:
            pil_image = pil_image.convert("RGB")

        # Get the size of the original image
        width, height = pil_image.size

        # Calculate the aspect ratio of the original image
        aspect_ratio = width / height

        # Calculate the new size based on the provided long side while preserving the aspect ratio
        if width > height:
            new_width = cover_long
            new_height = int(new_width / aspect_ratio)
        else:
            new_height = cover_long
            new_width = int(new_height * aspect_ratio)

        # Resize the image using the new size while preserving the aspect ratio
        pil_image = pil_image.resize((new_width, new_height), PILImage.LANCZOS)

        pil_image = ImageOps.exif_transpose(pil_image)

        pil_image = pil_image.convert('RGB')

        # Create a BytesIO object to store the resized image data
        resized_io = BytesIO()

        # Save the resized image to the BytesIO object
        try:
            pil_image.save(resized_io, format='AVIF', quality=cover_quality)
        except Exception as e:
            # Handle any exceptions that may occur during AVIF encoding
            print(f"AVIF encoding error: {e}")
            return None

        # Create a new InMemoryUploadedFile with the resized image data
        resized_file = InMemoryUploadedFile(
            resized_io,
            None,
            f"{self.cover.name.split('.')[0]}_resized.avif",
            'image/avif',
            resized_io.getbuffer().nbytes,
            None
        )

        # Update the cover field with the resized image
        self.cover = resized_file
        self.save()

        return self.cover

    def __str__(self):
        return self.name

    def publish(self):
        self.save()

    class Meta:
        verbose_name = _('Album')
        verbose_name_plural = _('Albums')


class MenuItem(models.Model):
    album = models.OneToOneField('Album', on_delete=models.CASCADE)
    name = models.CharField(verbose_name=_('Name'), max_length=120)
    order = models.PositiveIntegerField(verbose_name=_('Order'), default=0)
    privilege = models.BooleanField(verbose_name=_('Menu title privilege'), default=False)
    status = models.BooleanField(verbose_name=_('Visibility'), default=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.name


def image_path(instance, filename):
    # instance.album.slug contains the name of the Album
    # filename contains the original filename of the uploaded image
    return os.path.join('image', instance.album.slug, filename)


def thumbnail_path(instance, filename):
    # instance.album.slug contains the name of the Album
    # filename contains the original filename of the uploaded image
    return os.path.join('thumbnails', instance.album.slug, filename)


class Image(models.Model):
    name = models.CharField(verbose_name=_('Image name'), max_length=250, blank=True, null=True)

core/smartgallery/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import PasswordChangeForm
from .models import SiteSettings, Image, Album, SocialLinks
from django.forms import inlineformset_factory


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SiteSettingsForm(forms.ModelForm):
    class Meta:
        model = SiteSettings
        fields = (
            'title',
            'title_size',
            'title_delimiter',
            'menu_delimiter',
            'menu_items_size',
            'logo',
            'logo_width',
            'copyright',
            'topbar_bgcolor',
            'topbar_fcolor',
            'image_long',
            'thumbnail_long',
            'image_quality',
            'thumbnail_quality',
            'preserve_image_size',
            'show_social_links',
            'show_about_page',
            'show_timeline_page',
            'favicon',
            'default_language',
            'gle_analytics',
        )


class EditHTMLPages(forms.ModelForm):
    class Meta:
        model = SiteSettings
        fields = (
            'index_content',
            'about_content',
        )


class UserSettingsForm(UserChangeForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email')


class PasswordChangeCustomForm(PasswordChangeForm):
    pass


class CreateAlbumView(forms.ModelForm):
    class Meta:
        model = Album
        fields = [
            'name',
            'desc',
            'slug',
            'cover',
            'status',
        ]


class SocialForm(forms.ModelForm):
    class Meta:
        model = SocialLinks
        fields = [
            'name',
            'link',
            'icon',
        ]


class EditAlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = [
            'name',
            'slug',
            'desc',
            'desc_visible',
            'cover_visible',
            'cols_count_s',
            'cols_count_m',
            'cols_gap',
            'grid_type',
            'masonry_text_overlay',
            'image_border_radius',
            'status',
            'transition_anim',
            'cover',
            'meta_tags',
            'meta_desc',
        ]


class ImageForm(forms.ModelForm):
    album = forms.ModelChoiceField(queryset=Album.objects.all(), empty_label="Select an album", required=False)

    class Meta:
        model = Image
        fields = [
            'image',
            'album',
            'ytvideo',
            # 'pano_status',
        ]

core/smartgallery/templates/front/add_social.html
{% extends 'front/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<link rel="stylesheet" href="https://code.jquery.com/ui/edit_album.13.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
<div style="margin-top:50px;">
    <ul class="uk-child-width-expand uk-tab">
        <li><a href="{% url 'site_settings' %}">General settings</a></li>
        <li><a href="{% url 'menu_settings' %}">Menu settings</a></li>
        <li class="uk-active"><a href="{% url 'add_social' %}">Social networks</a></li>
        <li class="uk-disabled"><a href="#">User settings</a></li>
    </ul>
</div>
<div class="uk-child-width-expand@s uk-text-left" uk-grid>
    <div>
        <div class="uk-card uk-card-default uk-card-body uk-width-expand@s">
            <h3>Add new social network</h3>
            <p>To add New Social Network link with icon choose icon from <a href="https://fontawesome.com/search" target="_blank">FontAwesome search</a></p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label class="uk-form-label">Name:</label>
                <div class="uk-form-controls">
                    <input type="text" id="name" name="name" required placeholder="Name, i.e. LinkedIn" class="item-name uk-input uk-form-width-large" style="margin:5px;border-radius:5px;">
                </div>
                <label class="uk-form-label">Link:</label>
                <div class="uk-form-controls">
                    <input type="text" id="link" name="link" placeholder="Link" class="item-name uk-input uk-form-width-large" style="margin:5px;border-radius:5px;">
                </div>
                <label class="uk-form-label">Icon:</label>
                <div class="uk-form-controls">
                    <input type="text" id="icon" name="icon" placeholder="FontAwesome Icon" class="item-name uk-input uk-form-width-large" style="margin:5px;border-radius:5px;">
                </div>
                <input class="uk-button uk-button-default" type="submit" value="ADD social Network" style="border-radius:5px;margin:5px;">
            </form>
        </div>
    </div>
    <div>
        <div class="uk-width-expand@m">
            <div class="uk-card uk-card-default uk-card-body" style="padding-bottom:120px;">
                <h3>Reorder and Edit Social Network items</h3>
                <p>To change the order of social items, drag name</p>
                <ul id="social-items"  style="list-style-type: none;">
                    {% for SocialLinks in social %}
                    <li data-social-item-id="{{ SocialLinks.id }}" style="cursor: move;">
                        <span style="font-size:16pt;">#</span>
                            <input type="text" value="{{ SocialLinks.name }}" placeholder="Name, i.e. LinkedIn" class="item-name uk-input uk-form-width-small" style="margin:5px;border-radius:5px;">
                            <input type="text" value="{{ SocialLinks.link }}" placeholder="Link" class="item-link uk-input uk-form-width-medium" style="margin:5px;border-radius:5px;">
                            <input type="text" value="{{ SocialLinks.icon }}" placeholder="Icon" class="item-icon uk-input uk-form-width-medium" style="margin:5px;border-radius:5px;">
                            <button class="save-button uk-button uk-button-small" data-social-item-id="{{ SocialLinks.id }}" uk-tooltip="Save item" style="border-radius:5px;background-color: white;border:1px solid grey">Save</button>
                            <a href="{% url 'delete_social_item_name' id=SocialLinks.id %}"><button class="uk-button uk-button-small" uk-tooltip="Delete item" style="border-radius:5px;background-color: white;border:1px solid grey;">Delete</button></a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
            $("#social-items").sortable();

            // Add event listener for the "Save" button clicks
            $(".save-button").on("click", function() {
                var itemId = $(this).data("social-item-id");
                var newName = $(this).siblings(".item-name").val();
                var newLink = $(this).siblings(".item-link").val();
                var newIcon = $(this).siblings(".item-icon").val();

                // Send the updated name to the server-side using AJAX
                $.ajax({
                    type: "POST",
                    url: "{% url 'update_social_item_name' %}",
                    data: {
                        "item_id": itemId,
                        "new_name": newName,
                        "new_link": newLink,
                        "new_icon": newIcon,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    },
                    success: function(response) {
                        // Handle the success response, if needed
                        console.log(response);
                        UIkit.notification({message: 'Item saved', status: 'success', timeout: 1000});
                    },
                    error: function(error) {
                        // Handle the error response, if needed
                        console.error(error);
                    }
                });
            });
        });
        $(function() {
            $("#social-items").sortable({
                update: function(event, ui) {
                    var newOrder = $(this).sortable('toArray', { attribute: 'data-social-item-id' });

                    $.ajax({
                        type: 'POST',
                        url: '{% url 'update_social_order' %}',
                        data: {
                            'new_order': newOrder,
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        },
                        success: function() {
                            UIkit.notification({message: 'Item saved', status: 'success', timeout: 1000});
                        },
                        error: function() {
                            // You may choose to handle error response if needed.
                        }
                    });
                }
            });
        });
</script>
{% endif %}
{% endblock %}
{% block copyright %}
{{settings.copyright}}
{% endblock %}

core/smartgallery/templates/front/album.html
{% extends 'front/base.html' %}
{% load addon_filters %}
{% load i18n %}
{% block content %}
{% if album.status or user.is_authenticated %}
<title>{{album.name}} | {{settings.title}}</title>
<meta name="description" content="{{album.meta_desc}}" />
<meta name="keywords" content="{{album.meta_tags}}" />
<style>
.album-cover-grad img {
    -webkit-mask-image:-webkit-gradient(linear, left top, left bottom, from(rgba(0,0,0,1)), to(rgba(0,0,0,0)));
    object-fit:cover;
    object-position: 35% 65%;
    height:400px;
    width:100%;
  }
  .centered-icon {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
</style>
<div class="gallery">
    {% if album.cover_visible %}
    {% if album.cover %}
    <div class="album-cover-grad">
        <img src="{{album.cover.url}}">
    </div>
    {% endif %}
    {% endif %}
    <h{{settings.title_size}} class="uk-text-bolder footer uk-animation-fade">{{ settings.title_delimiter }} {{ album.name|upper }} {{ settings.title_delimiter }}</h{{settings.title_size}}>
    {% if album.desc_visible %}
    <blockquote class="footer" style="padding: 0 3% 0 3%">
        <p class="uk-margin-small-bottom"><q>{{album.desc}}</q></p>
    </blockquote>
    {% endif %}
    {% if album.get_grid_type_display == 'grid' %}
    {% include 'front/show_grids/grid.html' %}
    {% elif album.get_grid_type_display == 'masonry (beta)' %}
    {% include 'front/show_grids/masonry.html' %}
    {% endif %}
</div>
</div>
{% else %}
 <p class="uk-flex uk-flex-center">{% trans "This content is only visible to authenticated users." %}</p>
{% endif %}
{% endblock %}
{% block copyright %}
{{settings.copyright}}
{% endblock %}

core/smartgallery/templates/front/create_album.html
{% extends 'front/base.html' %}
{% block content %}
{% load i18n %}
{% if user.is_authenticated %}
<title>Create Album | {{settings.title}}</title>
<div class="uk-child-width-expand@s uk-text-center" uk-grid style="padding: 50px 100px 0px 100px;">
    <div>
        <div class="uk-card uk-card-default uk-card-body" style="text-align: left;">
            <form method="post" enctype="multipart/form-data" class="uk-grid-small" uk-grid>
                {% csrf_token %}

                <legend class="uk-legend">{% trans "Create Album" %}</legend>

                <div class="uk-margin uk-width-1-2@s">
                    <input class="uk-input" type="text" placeholder='{% trans "Album name" %}' id="name" name="name" required>
                </div>

                <div class="uk-margin uk-width-1-2@s">
                    <input class="uk-input" type="text" placeholder='{% trans "Album slug" %}' id="slug" name="slug" required>
                </div>
                {% if error_msg %}
                <p class="uk-text-danger">{{ error_msg }}</p>
                {% endif %}

                <div class="uk-margin uk-width-1-1">
                    <textarea class="uk-textarea" rows="5" placeholder='{% trans "Album description" %}' id="desc" name="desc"></textarea>
                </div>

                <div class="uk-margin uk-width-1-1@s">
                    <input type="file" id="cover" name="cover" accept="image/png, image/jpeg, image/webp, image/bmp" >
                </div>


                <div class="uk-margin uk-width-1-1@s">
                    <label><input class="uk-checkbox" type="checkbox" id="status" name="status" checked> {% trans "Album visibility" %}</label>
                </div>

                <br />
                <input class="uk-button uk-button-default" type="submit" value='{% trans "Create new album" %}'>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}
{% block copyright %}
{{settings.copyright}}
{% endblock %}

core/smartgallery/templates/front/edit_about.html
{% extends 'front/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="uk-margin uk-width-1-1@s" style="margin-top:0px !important;">
    <div>
        <div class="uk-card uk-card-default uk-card-body" style="text-align: left;">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <input class="uk-button uk-button-default" type="submit" value="UPDATE ABOUT PAGE">
        </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}
{% block copyright %}
{{settings.copyright}}
{% endblock %}

core/smartgallery/templates/front/edit_album.html
{% extends 'front/base.html' %}
{% block content %}
{% load static %}
{% load i18n %}
{% if user.is_authenticated %}
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/flatpickr.min.css' %}">
<script src="{% static 'js/flatpickr.js' %}"></script>
<title>{{settings.title}}</title>
<h2 class="uk-text-bolder footer uk-animation-fade">{{ settings.title_delimiter }} {% trans "Edit" %} {{ album.name }} {{ settings.title_delimiter }}</h2>
<div class="uk-child-width-expand@s uk-text-center" uk-grid style="padding: 0px 30px 0px 30px;">
    <div class="uk-margin uk-width-2-3@s">
        <div class="gallery">
            {% if album.get_grid_type_display == 'grid' %}
            {% include "front/edit_album/grid.html" %}
            {% elif album.get_grid_type_display == 'masonry (beta)' %}
            {% include "front/edit_album/masonry.html" %}
            {% endif %}
        </div>
    </div>
    <div class="uk-margin uk-width-1-3@s" style="margin-top:0px !important;">
        <div>
            <div class="uk-card uk-card-default uk-card-body" style="text-align: left;">
                {% include 'front/edit_album/form.html' %}
            </div>
        </div>
    </div>
</div>
{% include "front/scripts/edit_album_scripts.html" %}
{% endif %}
{% endblock %}
{% block copyright %}
{{settings.copyright}}
{% endblock %}

core/smartgallery/templates/front/index_safe.html
{{ rendered_content|safe }}

core/smartgallery/templates/front/index_test.html
{{ rendered_content|safe }}

core/smartgallery/templates/front/upload.html
{% extends 'front/base.html' %}
{% block content %}
{% load i18n %}
{% if user.is_authenticated %}
<title>{% trans "Upload Images" %} | {{settings.title}}</title>
<div class="footer">
    <h1>{% trans "Upload Images" %}</h1>
    <form method="post" enctype="multipart/form-data" onsubmit="return validateForm()">
        {% csrf_token %}
        <input required name="image" type="file" multiple id="id_image" accept="image/png, image/jpeg, image/webp, image/bmp">
        <select name="album" id="id_album" required>
            <option value="none" disabled selected>{% trans "Select an Album" %}...</option>
            {% for album in albums %}
            <option value="{{album.name}}">{{album.name}}</option>
            {% endfor %}
        </select>
        <br>
<!--        <label class="uk-form-label">{% trans "It's a panorama image" %}:</label>-->
<!--        <div class="uk-form-controls">-->
<!--            <input type="checkbox" id="pano_status" name="pano_status" class="item-name uk-checkbox uk-form-width-large" {% if image.pano_status %}checked{% endif %}>-->
<!--        </div>-->
        <p>{% trans "If the field below (Youtube Video) is filled, then the uploaded photo will serve as a preview." %}</p>
        <label style="font-size:10pt;">{% trans "Youtube Video link" %}: </label><input name="ytvideo" type="text" id="id_ytvideo">
        <br>
        <input type="submit" value='{% trans "Upload" %}'>
    </form>
</div>
<script>
    function validateForm() {
        const selectedAlbum = document.getElementById('id_album').value;
        if (selectedAlbum === 'none') {
            UIkit.notification({message: 'Select an album from dropdown menu!', status: 'warning', timeout: 1000});
            return false; // Prevent form submission
        }
        return true; // Allow form submission
    }
</script>
{% endif %}
{% endblock %}
{% block copyright %}
{{settings.copyright}}
{% endblock %}