core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('smartgallery.urls')),
]

admin.site.site_header = "SmartGallery CMS"
admin.site.site_title = admin.site.site_header
admin.site.index_title = f"Welcome to {admin.site.site_header}"

core/smartgallery/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index_page, name='index_page'),
    path('p/about/', views.about, name='about'),
    path('<slug:album_slug>/', views.show_albums, name='show_albums'),
    path('sys/<int:album_id>', views.edit_album, name='edit_album'),
    path('sys/delete_image/<int:image_id>', views.delete_image, name='delete_image'),
    path('sys/delete_all_album_images/<int:album_id>/', views.delete_all_album_images, name='delete_all_album_images'),
    path('sys/delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('sys/delete_all_album_hidden_images/<int:album_id>/', views.delete_all_album_hidden_images, name='delete_all_album_hidden_images'),
    path('sys/create_album/', views.create_album, name='create_album'),
    path('sys/update_image_order', views.update_image_order, name='update_image_order'),
    path('sys/update_image_name/<int:photo_id>', views.update_image_name, name='update_image_name'),
    path('sys/update_image_exif/<int:photo_id>', views.update_image_exif, name='update_image_exif'),
    path('sys/change_album/<int:photo_id>/<int:album_id>', views.change_album, name='change_album'),
    path('sys/images/<int:image_id>/change_visibility', views.change_visibility, name='change_visibility'),
    path('sys/login', views.a_login, name='a_login'),
    path('sys/logout/', views.a_logout, name='a_logout'),
    path('sys/settings', views.site_settings, name='site_settings'),
    path('sys/template_settings', views.template_settings, name='template_settings'),
    path('sys/menu_settings', views.menu_settings, name='menu_settings'),
    path('sys/social_settings/', views.social_settings, name='social_settings'),
    path('sys/user_settings/', views.user_settings, name='user_settings'),
    path('sys/update_menu_order/', views.update_menu_order, name='update_menu_order'),
    path('sys/update_social_order/', views.update_social_order, name='update_social_order'),
    path('sys/update_menu_item_name/', views.update_menu_item_name, name='update_menu_item_name'),
    path('sys/update_social_item_name/', views.update_social_item_name, name='update_social_item_name'),
    path('sys/delete_social_item_name/<int:id>', views.delete_social_item_name, name='delete_social_item_name'),
    path('sys/delete_current_logo/', views.delete_current_logo, name='delete_current_logo'),
    path('p/timeline/', views.timeline, name='timeline'),
    path('sys/upload/', views.upload_images, name='upload_images'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/smartgallery/models.py
import datetime
import os
import pillow_avif
from PIL import Image
from io import BytesIO
from PIL import ImageOps
from PIL.ExifTags import TAGS
from PIL import Image as PILImage, ExifTags
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models


class SiteSettings(models.Model):
    title = models.CharField(verbose_name=_('Website title'), max_length=100, blank=True, default='Smart Photo Gallery')
    logo = models.FileField(verbose_name=_('Site logo'), upload_to='logo/', blank=True)
    logo_width = models.PositiveIntegerField(verbose_name=_('Logo width, px'), blank=True, default=240)
    topbar_bgcolor = models.CharField(verbose_name=_('Top bar Background Color'), max_length=8, default="#B7C3F3", blank=True)
    topbar_fcolor = models.CharField(verbose_name=_('Top bar Font Color'), max_length=8, default="black", blank=True)
    copyright = models.CharField(
        verbose_name=_('Copyright text'),
        max_length=1000,
        blank=True,
        default=f'Smart Photo Gallery - {datetime.datetime.now().year}'
    )
    menu_delimiter = models.CharField(verbose_name=_('Menu delimiter'), max_length=5, blank=True, default=' | ')
    title_delimiter = models.CharField(verbose_name=_('Title delimiter'), max_length=5, blank=True, default=' · ')
    title_size = models.PositiveIntegerField(verbose_name=_('Title size, h1-6'), blank=True, default=2)
    menu_items_size = models.PositiveIntegerField(verbose_name=_('Menu item size, pt'), blank=True, default=18)
    image_long = models.PositiveIntegerField(verbose_name=_('Big image long side, px'), blank=False, default=1600)
    thumbnail_long = models.PositiveIntegerField(verbose_name=_('Preview long side, px'), blank=False, default=800)
    image_quality = models.PositiveIntegerField(verbose_name=_('Big image quality, %'), blank=False, default=90)
    thumbnail_quality = models.PositiveIntegerField(verbose_name=_('Preview image quality, %'), blank=False, default=80)
    preserve_image_size = models.BooleanField(verbose_name=_('Preserve big image size and quality'), default=False)
    show_social_links = models.BooleanField(verbose_name=_('Show social links'), default=False)
    show_about_page = models.BooleanField(verbose_name=_('Show About Me'), default=False)
    show_timeline_page = models.BooleanField(verbose_name=_('Show Timeline'), default=False)
    favicon = models.FileField(verbose_name=_('Favicon'), upload_to='favicon/', max_length=250, blank=True)
    LANGUAGE_CHOICES = [
        ('en', 'English'),
        ('ru', 'Russian'),
    ]
    default_language = models.CharField(
        verbose_name=_('Default Language'),
        max_length=2,
        choices=LANGUAGE_CHOICES,
        default='en',  # Set the default language
    )
    gle_analytics = models.TextField(verbose_name=_('Google analytics code'), max_length=1000, blank=True)
    index_content = models.TextField(verbose_name=_('Index page content'), max_length=20000, blank=True, default='')
    about_content = models.TextField(verbose_name=_('About me page content'), max_length=20000, blank=True, default='')

    def render_index_content(self, context=None):
        from django.template import Template, Context

        if context is None:
            context = {}

        template = Template(self.index_content)
        context = Context(context)
        return template.render(context)

    def render_about_content(self, context=None):
        from django.template import Template, Context

        if context is None:
            context = {}

        template = Template(self.about_content)
        context = Context(context)
        return template.render(context)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Site settings')
        verbose_name_plural = _('Site settings')


class SocialLinks(models.Model):
    name = models.CharField(verbose_name=_('Name'), max_length=80, blank=False)
    link = models.CharField(verbose_name=_('Link'), max_length=200, blank=True)
    icon = models.CharField(verbose_name=_('Icon'), max_length=100, blank=True)
    order = models.PositiveIntegerField(verbose_name=_('Order'), default=0)

    def __str__(self):
        return str(self.name)

    def publish(self):
        self.save()

    class Meta:
        verbose_name = _('Social Link')
        verbose_name_plural = _('Social Links')


class Album(models.Model):
    slug = models.CharField(verbose_name=_('SLUG'), max_length=128, blank=False, null=False)
    name = models.CharField(verbose_name=_('Album name'), max_length=128, blank=False, null=False)
    meta_tags = models.CharField(verbose_name=_('Meta keywords'), max_length=1000, blank=True)
    meta_desc = models.CharField(verbose_name=_('Meta description'), max_length=1000, blank=True)
    desc = models.TextField(
        verbose_name=_('About album'),
        max_length=2000,
        default='Album description can be changed in Album settings',
        blank=True,
        null=True
    )
    desc_visible = models.BooleanField(verbose_name=_('Description visibility'), default=True)
    cols_count_s = models.PositiveIntegerField(verbose_name=_('Columns count on mobile devices'), default=2)
    cols_count_m = models.PositiveIntegerField(verbose_name=_('Columns count'), default=3)
    cols_gap_size = [
        ('cl', "collapse"),
        ('sm', "small"),
        ('md', "medium"),
        ('lg', "large"),
    ]
    cols_gap = models.CharField(
        verbose_name=_('Columns gap'),
        max_length=2,
        choices=cols_gap_size,
        default='sm',
    )
    grid_types = [
        ('grid', "grid"),
        ('masonry', "masonry (beta)"),
    ]
    grid_type = models.CharField(
        verbose_name=_('Grid type'),
        max_length=10,
        choices=grid_types,
        default='grid',
    )
    masonry_text_overlay = models.BooleanField(verbose_name=_('Masonry text overlay'), default=True)
    image_border_radius = models.PositiveIntegerField(verbose_name=_('Images border radius, px'), default=0, blank=False)
    order = models.PositiveIntegerField(verbose_name=_('Order'), blank=True, null=True, default=0)
    status = models.BooleanField(verbose_name=_('Visibility'), default=True)
    transitions = [
        ('fade', "fade"),
        ('slide', "slide"),
        ('scale', "scale"),
    ]
    transition_anim = models.CharField(
        verbose_name=_('Image transition'),
        max_length=6,
        choices=transitions,
        default='slide',
    )
    cover = models.ImageField(upload_to='album_covers', blank=True, null=True)
    cover_visible = models.BooleanField(verbose_name=_('Cover visibility'), default=False)

    def resize_and_crop_cover(self, cover_long, cover_quality):
        # Open the original image using PIL
        pil_image = PILImage.open(self.cover.path)

        if pil_image.format in ["WEBP", "HEIC"]:
            pil_image = pil_image.convert("RGB")

        # Get the size of the original image
        width, height = pil_image.size

        # Calculate the aspect ratio of the original image
        aspect_ratio = width / height

        # Calculate the new size based on the provided long side while preserving the aspect ratio
        if width > height:
            new_width = cover_long
            new_height = int(new_width / aspect_ratio)
        else:
            new_height = cover_long
            new_width = int(new_height * aspect_ratio)

        # Resize the image using the new size while preserving the aspect ratio
        pil_image = pil_image.resize((new_width, new_height), PILImage.LANCZOS)

        pil_image = ImageOps.exif_transpose(pil_image)

        pil_image = pil_image.convert('RGB')

        # Create a BytesIO object to store the resized image data
        resized_io = BytesIO()

        # Save the resized image to the BytesIO object
        try:
            pil_image.save(resized_io, format='AVIF', quality=cover_quality)
        except Exception as e:
            # Handle any exceptions that may occur during AVIF encoding
            print(f"AVIF encoding error: {e}")
            return None

        # Create a new InMemoryUploadedFile with the resized image data
        resized_file = InMemoryUploadedFile(
            resized_io,
            None,
            f"{self.cover.name.split('.')[0]}_resized.avif",
            'image/avif',
            resized_io.getbuffer().nbytes,
            None
        )

        # Update the cover field with the resized image
        self.cover = resized_file
        self.save()

        return self.cover

    def __str__(self):
        return self.name

    def publish(self):
        self.save()

    class Meta:
        verbose_name = _('Album')
        verbose_name_plural = _('Albums')


class MenuItem(models.Model):
    album = models.OneToOneField('Album', on_delete=models.CASCADE)
    name = models.CharField(verbose_name=_('Name'), max_length=120)
    order = models.PositiveIntegerField(verbose_name=_('Order'), default=0)
    privilege = models.BooleanField(verbose_name=_('Menu title privilege'), default=False)
    status = models.BooleanField(verbose_name=_('Visibility'), default=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.name


def image_path(instance, filename):
    # instance.album.slug contains the name of the Album
    # filename contains the original filename of the uploaded image
    return os.path.join('image', instance.album.slug, filename)


def thumbnail_path(instance, filename):
    # instance.album.slug contains the name of the Album
    # filename contains the original filename of the uploaded image
    return os.path.join('thumbnails', instance.album.slug, filename)


class Image(models.Model):
    name = models.CharField(verbose_name=_('Image name'), max_length=250, blank=True, null=True)

core/smartgallery/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import PasswordChangeForm
from .models import SiteSettings, Image, Album, SocialLinks
from django.forms import inlineformset_factory


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SiteSettingsForm(forms.ModelForm):
    class Meta:
        model = SiteSettings
        fields = (
            'title',
            'title_size',
            'title_delimiter',
            'menu_delimiter',
            'menu_items_size',
            'logo',
            'logo_width',
            'copyright',
            'topbar_bgcolor',
            'topbar_fcolor',
            'image_long',
            'thumbnail_long',
            'image_quality',
            'thumbnail_quality',
            'preserve_image_size',
            'show_social_links',
            'show_about_page',
            'show_timeline_page',
            'favicon',
            'default_language',
            'gle_analytics',
        )


class EditHTMLPages(forms.ModelForm):
    class Meta:
        model = SiteSettings
        fields = (
            'index_content',
            'about_content',
        )


class UserSettingsForm(UserChangeForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email')


class PasswordChangeCustomForm(PasswordChangeForm):
    pass


class CreateAlbumView(forms.ModelForm):
    class Meta:
        model = Album
        fields = [
            'name',
            'desc',
            'slug',
            'cover',
            'status',
        ]


class SocialForm(forms.ModelForm):
    class Meta:
        model = SocialLinks
        fields = [
            'name',
            'link',
            'icon',
        ]


class EditAlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = [
            'name',
            'slug',
            'desc',
            'desc_visible',
            'cover_visible',
            'cols_count_s',
            'cols_count_m',
            'cols_gap',
            'grid_type',
            'masonry_text_overlay',
            'image_border_radius',
            'status',
            'transition_anim',
            'cover',
            'meta_tags',
            'meta_desc',
        ]


class ImageForm(forms.ModelForm):
    album = forms.ModelChoiceField(queryset=Album.objects.all(), empty_label="Select an album", required=False)

    class Meta:
        model = Image
        fields = [
            'image',
            'album',
            'ytvideo',
            # 'pano_status',
        ]

core/smartgallery/templates/front/show_grids/grid.html
{% load addon_filters %}
{% load static %}
<div class="uk-child-width-1-{{album.cols_count_s}}@s uk-child-width-1-{{album.cols_count_m}}@m uk-text-center uk-grid-{{album.get_cols_gap_display}}" uk-grid="masonry: false" uk-lightbox="animation:{{album.get_transition_anim_display}};">
  {% for image in images %}
  {% if not image.ytvideo %}
  <div>
    <a href="{{ image.image.url }}"
       data-caption="
            {% if image.latitude %}&lt;a href=&quot;https://www.google.com/maps/place/{{image.latitude|replace_commas_with_periods}},{{image.longitude|replace_commas_with_periods}}&quot; target=&quot;_blank&quot;&gt;&lt;u&gt;GEO Location Data&lt;/u&gt;
&lt;/a&gt;{% endif %}
            {{image.name|default_if_none:''}}
            {{image.camera_manufacturer|default_if_none:''}}
            {{image.camera_model|default_if_none:''}}
            {{image.focal_length|default_if_none:''}}
            {{image.exposure_time|default_if_none:''}}
            {{image.f_number|default_if_none:''}}
            {{image.iso_speed|default_if_none:''}}
            {{image.date_taken|date:'d-m-Y'|default_if_none:''}}
            ">
      <div class="uk-card uk-card-default uk-card-body card-md"
           style="background-image: url({%if image.thumbnail %}{{ image.thumbnail.url }}{% else %}{% static 'img/thumb_loading.jpg' %}{% endif %});border-radius:{% if album.image_border_radius %}{{album.image_border_radius}}{% else %}0{% endif %}px;" uk-scrollspy="cls: uk-animation-fade; repeat: false"></div>
    </a>
  </div>
  {% else %}
  <div>
    <a href="{{ image.ytvideo }}"
       data-caption="{{image.name|default_if_none:''}}">
      <div class="uk-card uk-card-default uk-card-body card-md"
           loading="lazy"
           style="background-image: url({%if image.thumbnail %}{{ image.thumbnail.url }}{% else %}{% static 'img/thumb_loading.jpg' %}{% endif %});border-radius:{% if album.imaglse_border_radius %}{{album.image_border_radius}}{% else %}0{% endif %}px;" uk-scrollspy="cls: uk-animation-fade; repeat: false">
        <svg class="centered-icon" xmlns="http://www.w3.org/2000/svg" height="6em" fill="red" viewBox="0 0 576 512"><path d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z"/></svg>
      </div>
    </a>
  </div>
  {% endif %}
  {% endfor %}
</div>

core/smartgallery/templates/front/show_grids/masonry.html
{% load addon_filters %}
{% load static %}
<style>
.masonry .grid__title {
  font-size: 24px;
  opacity:70%;
  font-weight: bold;
  margin: 0px 0px 10px 0px;
}
.masonry .grid__author {
  font-size: 14px;
  font-weight: 300;
}
.masonry .grid__link {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
}
.masonry .grid__body {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  padding: 30px 30px;
  color: #fff;
  display: flex;
  flex-direction: column;
}
.mt-auto {
  margin-top: auto;
}
.centered-icon {
 position: absolute;
 top: 50%;
 left: 50%;
 transform: translate(-50%, -50%);
</style>
<div class=" masonry uk-child-width-1-{{album.cols_count_s}}@s uk-child-width-1-{{album.cols_count_m}}@m uk-text-center uk-grid-{{album.get_cols_gap_display}}" uk-grid="masonry: true" uk-lightbox="animation:{{album.get_transition_anim_display}};">
    {% for image in images %}
    {% if not image.ytvideo %}
    <a href="{{ image.image.url }}" data-caption="
    {% if image.latitude %}&lt;a href=&quot;https://www.google.com/maps/place/{{image.latitude|replace_commas_with_periods}},{{image.longitude|replace_commas_with_periods}}&quot; target=&quot;_blank&quot;&gt;&lt;u&gt;GEO Location Data&lt;/u&gt;
&lt;/a&gt;{% endif %}
            {{image.name|default_if_none:''}}
            {{image.camera_manufacturer|default_if_none:''}}
            {{image.camera_model|default_if_none:''}}
            {{image.focal_length|default_if_none:''}}
            {{image.exposure_time|default_if_none:''}}
            {{image.f_number|default_if_none:''}}
            {{image.iso_speed|default_if_none:''}}
            {{image.date_taken|date:'d-m-Y'|default_if_none:''}}
    ">
        <div class="grid">
            <img src="{%if image.thumbnail %}{{ image.thumbnail.url }}{% else %}{% static 'img/thumb_loading.jpg' %}{% endif %}" class="grid__image" id="image{{image.id}}" loading="lazy" style="border-radius:{% if album.image_border_radius %}{{album.image_border_radius}}{% else %}0{% endif %}px;">
            <div class="grid__body">
                <div class="relative">
                    {% if album.masonry_text_overlay %}
                    <h1 class="grid__title" id="title{{image.id}}">{{ image.name|default_if_none:'' }}</h1>
                    {%endif%}
                </div>
            </div>
        </div>
    </a>
    {% else %}
    <a href="{{ image.ytvideo }}" data-caption="{{ image.name|default_if_none:'' }}">
        <div class="grid">
            <img src="{%if image.thumbnail %}{{ image.thumbnail.url }}{% else %}{% static 'img/thumb_loading.jpg' %}{% endif %}" class="grid__image" id="image{{image.id}}" loading="lazy" style="border-radius:{% if album.image_border_radius %}{{album.image_border_radius}}{% else %}0{% endif %}px;">
            <svg class="centered-icon" xmlns="http://www.w3.org/2000/svg" height="6em" fill="red" viewBox="0 0 576 512"><path d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z"/></svg>
            <div class="grid__body">
                <div class="relative">
                    {% if album.masonry_text_overlay %}
                    <h1 class="grid__title" id="title{{image.id}}">{{ image.name|default_if_none:'' }}</h1>
                    {%endif%}
                </div>
            </div>
        </div>
    </a>
    {% endif %}
    {% if album.masonry_text_overlay %}
    <script>
    document.addEventListener("DOMContentLoaded", function () {
        {% for image in images %}
        const image{{image.id}} = document.getElementById("image{{image.id}}");
        const title{{image.id}} = document.getElementById("title{{image.id}}");

        const imageColor{{image.id}} = getAverageRGB(image{{image.id}});
        const brightness{{image.id}} = calculateBrightness(imageColor{{image.id}});

        if (brightness{{image.id}} > 127) {
            title{{image.id}}.style.color = "black";
        } else {
            title{{image.id}}.style.color = "white";
        }
        {% endfor %}
    });

    function getAverageRGB(img) {
        const canvas = document.createElement("canvas");
        canvas.width = img.width;
        canvas.height = img.height;

        const ctx = canvas.getContext("2d");
        ctx.drawImage(img, 0, 0, img.width, img.height);

        const imageData = ctx.getImageData(0, 0, img.width, img.height);
        const data = imageData.data;

        let r = 0;
        let g = 0;
        let b = 0;

        for (let i = 0; i < data.length; i += 4) {
            r += data[i];
            g += data[i + 1];
            b += data[i + 2];
        }

        const pixelCount = data.length / 4;
        r = Math.round(r / pixelCount);
        g = Math.round(g / pixelCount);
        b = Math.round(b / pixelCount);

        return [r, g, b];
    }

    function calculateBrightness(rgb) {
        return (rgb[0] * 299 + rgb[1] * 587 + rgb[2] * 114) / 1000;
    }
</script>
    {%endif%}
    {% endfor %}
</div>